# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/camera

PRODUCT_COPY_FILES += \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libcamera_ispinterface_jni.xiaomi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamera_ispinterface_jni.xiaomi.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libged_kpi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libged_kpi.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libged_sys.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libged_sys.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libgui-xiaomi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgui-xiaomi.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libgui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgui.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libgui_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgui_vendor.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/libmtkisp_metadata_sys.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkisp_metadata_sys.so \
    vendor/xiaomi/camera/proprietary/vendor/lib64/vendor.mediatek.hardware.camera.isphal@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.mediatek.hardware.camera.isphal@1.0.so

PRODUCT_PACKAGES += \
    MiuiCamera
